# Generated by Django 5.0.3 on 2024-04-01 06:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default_shop.png', upload_to='shop')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
